#!/bin/bash

# Make sure we're not confused by old, incompletely-shutdown httpd
# context after restarting the container.  httpd won't start correctly
# if it thinks it is already running.
rm -rf /run/httpd/*

export OPTIONS="${OPTIONS} ${APACHE_OPTIONS}"
scl enable httpd24 apachectl
